info:
  contact: {}
paths: {}
swagger: "2.0"
basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@auth-service.com
    name: API Support
    url: https://github.com/perfect1337/auth-service/issues
  description: API for user authentication, registration and JWT token management
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://github.com/perfect1337/auth-service
  title: Auth Service API
  version: "1.0"
paths: {}
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
